i# Generated by Django 5.0.6 on 2024-07-27 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0004_remove_movieorder_snack_movieorder_snacks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieorder',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 27)),
        ),
        migrations.AlterField(
            model_name='snackorder',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 27)),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 27)),
        ),
    ]
